# https://docs.docker.com/go/compose-spec-reference/
# https://github.com/docker/awesome-compose
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  api:
    build:
      context: ./api/.
      target: final
    depends_on:
      - "mongo"
    ports:
      - 42069:42069
    environment:
      MONGODB_URI: mongodb://mongo:27017
    develop:
      watch:
        - action: rebuild
          path: ./api/

  # ui:
  #   build:
  #     context: ./ui/.
  #     target: final
  #   depends_on:
  #     - "api"
  #   ports:
  #     - 8080:8080
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./ui/

  collector:
    build:
      context: ./collector/.
      target: final
    depends_on:
      - "api"
    environment:
      MONGODB_URI: mongodb://mongo:27017
    develop:
      watch:
        - action: rebuild
          path: ./collector/
