# https://docs.docker.com/go/compose-spec-reference/
# https://github.com/docker/awesome-compose
services:
  api:
    build:
      context: ./api/.
      target: final
    depends_on:
      - "mongo"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
    develop:
      watch:
        - action: rebuild
          path: ./api/

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
